### ISSUE TITLE
Link para Repositório do seu Projeto

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#34]
Inclua como comentário abaixo um link para o repositório Github que será utilizado pelo seu projeto. Se o repositório for privado, não esqueça de me incluir como colaborador. 

O formato a ser informado é o seguinte: 

| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| ------ | ------ |
| AlgumNome | Leopoldo (lmt) | Outro Nome (on) | https://www.github.com/leopoldomt/nome |

**Comment by heitorado** [comment]
| Rainmember | Heitor (hscs) | Rafael (rma7) | https://github.com/heitorado/Rainmember |

**Comment by marcellocordeiro** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| --- | --- | --- | --- |
| Travel Diary | Marcello (msc3) | Rodrigo (rcrs3) | https://github.com/marcellocordeiro/travel-diary |

**Comment by akai16** [comment]
| Bookbook | Gabriel Firmino (gfg2) | Livisghton (lksa) | https://github.com/akai16/Bookbook |

**Comment by wba25** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| ------------- | ------------- | ------------- | ------------- |
| Recipes by Ingredients | Wellington Almeida (wba) |  |  https://github.com/wba25/recipes-by-ingredients-app |

**Comment by mbs8** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| ------ | ------ |
|ListDay | Matheus Branco (mbs8) | Leandro Andrade (lad) | https://github.com/mbs8/ListDay |

**Comment by mbs8** [comment]
| Projeto | Nome (loginCIn) 1     | Nome (loginCIn) 2     | Link Repositório                |
| ------- | --------------------- | --------------------- | ------------------------------- |
| ListDay | Matheus Branco (mbs8) | Leandro Andrade (lad) | https://github.com/mbs8/ListDay |

**Comment by tancredosouza** [comment]
Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório
-- | -- | -- | --
Appersonal Trainer | Tantan (tjssj) | Diogo Rodrigues (dor) | https://github.com/tancredosouza/if710projeto

**Comment by jailjr** [comment]
Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório
-- | -- | -- | --
Doctor Reviewer | Jailson Gomes  (jjgsj) | João Amaro (jaab) | https://github.com/jailjr/Componentes

**Comment by DouglasSL** [comment]
| Projeto | Nome 1 | Nome 2 | Link Repositório |
| ------ | ------ | ------ | ------ |
| Aquê! | Douglas Soares (dsl) | Jônatas Clementino (joc) | https://github.com/DouglasSL/aque |

**Comment by rpss2** [comment]
| Prepi | Ramom Pereira (rpss) | Daniel Filgueira (dfb2) | https://github.com/rpss2/prepi-android |

**Comment by jfmrm** [comment]
Projeto | Nome1 | Nome 2 | Link Repositório |
| ------ | ------ | --------- | ---------------- |
Vitaes | João Filipe Moura (jfmrm) | Ramon Saboya (rsg3) | https://github.com/NeverDefineUs/vitaes-android

**Comment by ismaeljunior** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| ------ | ------ |
| Vacinou! | Ismael Rufino (iraj) | José Raphael (jrds) | https://github.com/ismaeljunior/projetovacina |

**Comment by ismaeljunior** [comment]
| Vacinou! | Ismael Rufino (iraj) | José Raphael (jrds) | https://github.com/ismaeljunior/projetovacina |

**Comment by b-bt** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| --- | --- | --- | --- | 
| Wakey | Bruno Barbosa (bbt) | José Murilo (jmsmf) | https://github.com/tbbruno/wakey |

**Comment by vrvs** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| ------ | ------ |  ------ |  ------ |
| GeoLock Intelligence | Valdemiro Vieira (vrvs) | Rodrigo de Lima (rlo) | https://github.com/vrvs/GeoLock |

**Comment by luucasv** [comment]
Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório 
-------- | -------------------- | -------------------- | ------------------ 
RadioStreamer | Lucas Santana (lvcs) | Adilson (assj2) | https://github.com/luucasv/radioStreamer

**Comment by lcc** [comment]
|DeejAI| Lucas Cabral(lcc4) | Victor Niceas() | https://github.com/LucasCCabral/deejai/|

**Comment by adecarli** [comment]
Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório
:--------: | :--------------------: | :--------------------: | :------------------:
Story Interactor | André De' Carli (acms) | Luca Ananias (lams3) | https://github.com/adecarli/story-interactor

**Comment by mirianes** [comment]
| Recife e Seus Contos | Miriane Silva (mstn) | https://github.com/mirianes/Recife-e-Seus-Contos-Android |

**Comment by ClaudioCarvalhoo** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| ------ | ------ | ------ | ------ |
| Pokédex Trivia Android | Claudio Carvalho (cco2) | Henríque Caúla (lhtc) | https://github.com/ClaudioCarvalhoo/pokedex-trivia-android |

**Comment by wilquerlima** [comment]
| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
| ------ | ------ | ------ | ------ |
| TuristAê | Edjan (esvm) | Wilquer (wtl) | https://github.com/wilquerlima/TuristAe |

**Comment by pamella** [comment]
<center>

| Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório |
|:-------------:|:-------------:| :-------------: |:-------------: |
| Gerenciador de Gastos | Pamella Bezerra (pbsf2) | Victor Aguiar (vag2) | https://github.com/pamella/app-gerenciador-de-gastos |

</center>

**Comment by riqmariz** [comment]
Projeto | Nome (loginCIn) 1 | Nome (loginCIn) 2 | Link Repositório
-- | -- | -- | --
Myaa - My anime app | Henrique Mariz (ham2) | Lucas Lin (lml) | https://github.com/riqgod/Myanimeapp

**Comment by mcnl** [comment]
| __Projeto__ | __Nome<br /> (loginCIn) 1__ |  __Nome <br />(loginCIn) 2__  | __Repositório__ |
|-------------|------------|------------|------------|
| 1% - Plug Searcher    | Matheus Casa Nova da Luz<br />(mcnl)| Vinicius Bezerra<br />(vbas)     |[https://github.com/mcnl/onepercent](https://github.com/mcnl/onepercent  )   |

**Comment by MichaelBarney** [comment]
| Cronometro Enem | Michael Barney (mbgj) |    |   https://github.com/MichaelBarney/CronometroENEM-Android |
