### ISSUE TITLE
Discussão - Processamento & Desempenho

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#35]
Por favor, escolham um dos temas disponíveis abaixo: 

1. Apresentação e Demonstração de Android Vitals - https://developer.android.com/topic/performance/vitals/
2. Apresentação e Demonstração do Android Profiler - CPU & Device Activity - https://developer.android.com/studio/profile/android-profiler
~3. Coletar boas práticas de desenvolvimento visando desempenho e implementar demonstração - Por exemplo: https://heartbeat.fritz.ai/increasing-performance-in-an-android-application-1086640aeef~
4. Apresentação e Discussão de Artigo Acadêmico: _An Empirical Study of the Performance Impacts of Android Code Smells_ - https://ieeexplore.ieee.org/document/7832968
~5. Apresentação e Discussão de Artigo Acadêmico: _An Empirical Study on the Impact of Android Code Smells on Resource Usage_ - https://pdfs.semanticscholar.org/0195/5b3356063d5126b67e645fdc36dff382dbed.pdf~

@Danielfib @rpss2 @marcellocordeiro @rcrs3

**Comment by r-carneiro** [comment]
@rcrs3 e @marcellocordeiro: 3 - Coletar boas práticas de desenvolvimento visando desempenho e implementar demonstração - Por exemplo

**Comment by rpss2** [comment]
@Danielfib @rpss2: 5 - Apresentação e Discussão de Artigo Acadêmico: An Empirical Study on the Impact of Android Code Smells on Resource Usage.

**Comment by leopoldomt** [comment]
Obrigado @r-carneiro e @rpss2

**Comment by Danielfib** [comment]
[Android Smells.pptx](https://github.com/if710/if710.github.io/files/3751099/Android.Smells.pptx)

**Comment by leopoldomt** [comment]
Obrigado, @Danielfib

**Comment by marcellocordeiro** [comment]
[Increasing performance in an Android application.pdf](https://github.com/if710/if710.github.io/files/3751990/Increasing.performance.in.an.Android.application.pdf)

**Comment by leopoldomt** [comment]
Obrigado @marcellocordeiro
