### ISSUE TITLE
Discussão - Memória

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#36]
Por favor, escolham um dos temas disponíveis abaixo:

1. ~Criação e apresentação de um aplicativo ilustrando anti-patterns que causam memory leak, ilustrados por meio do Memory Profiler do Android Studio (ex.: https://android.jlelse.eu/memory-leak-patterns-in-android-4741a7fcb570 e https://proandroiddev.com/everything-you-need-to-know-about-memory-leaks-in-android-d7a59faaf46a)~
2. ~Apresentação e demonstração da ferramenta LeakCanary 2.0 - https://square.github.io/leakcanary/~
3. ~Apresentação e discussão do artigo acadêmico: "Characterizing and detecting resource leaks in android applications" (ASE'13). https://doi.org/10.1109/ASE.2013.6693097~
4. Apresentação e discussão do artigo acadêmico: "Static analysis of context leaks in android applications" (ICSE-SEIP '18). DOI: https://doi.org/10.1145/3183519.3183530
5. Apresentação e discussão do artigo acadêmico: "How developers micro-optimize Android apps" Journal of Systems and Software 130, C (August 2017), 1-23. DOI: https://doi.org/10.1016/j.jss.2017.04.018

@VictorAguiarGuedes @Pamella @mirianes @esvm @wilquerlima

**Comment by VictorAguiarGuedes** [comment]
@VictorAguiarGuedes e @pamella: 2. Apresentação e demonstração da ferramenta LeakCanary 2.0 - https://square.github.io/leakcanary/

**Comment by wilquerlima** [comment]
@esvm @wilquerlima 1.Criação e apresentação de um aplicativo ilustrando anti-patterns que causam memory leak, ilustrados por meio do Memory Profiler do Android Studio (ex.: https://android.jlelse.eu/memory-leak-patterns-in-android-4741a7fcb570 e https://proandroiddev.com/everything-you-need-to-know-about-memory-leaks-in-android-d7a59faaf46a)

**Comment by mirianes** [comment]
3. Apresentação e discussão do artigo acadêmico: "Characterizing and detecting resource leaks in android applications" (ASE'13).
