### ISSUE TITLE
Discussão - Energia

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#37]
Por favor, escolham um dos temas disponíveis abaixo:

1. Criação e apresentação de um aplicativo ilustrando anti-patterns relacionados a eficiência energética, ilustrados por meio do Energy Profiler do Android Studio (ex.: https://developer.android.com/studio/profile/energy-profiler) 
2. ~Apresentação e discussão do artigo acadêmico: "Catalog of Energy Patterns for Mobile Applications" accepted at Empirical Software Engineering - https://arxiv.org/pdf/1901.03302.pdf e https://tqrg.github.io/energy-patterns/#/~
3. ~Apresentação e discussão do artigo acadêmico: "An exploratory study on assessing the energy impact of logging on Android applications" Empirical Software Engineering June 2018, Volume 23, Issue 3, pp 1422–1456. https://doi.org/10.1007/s10664-017-9545-x~
4. ~Apresentação e discussão do artigo acadêmico: "ServDroid: detecting service usage inefficiencies in Android applications" (ESEC/FSE 2019). DOI: https://doi.org/10.1145/3338906.3338950~
5. Apresentação e discussão do artigo acadêmico: "µDroid: an energy-aware mutation testing framework for Android" (ESEC/FSE 2017). DOI: https://doi.org/10.1145/3106237.3106244

Para outros artigos, acessem: https://github.com/luiscruz/awesome-mobile-app-energy-papers.

@stepnus @ismaeljunior @DouglasSL @JonatasDeOliveira @mcnl @vbsilva @orlandoaceto

**Comment by ismaeljunior** [comment]
@ismaeljunior e @stepnus: 3 Apresentação e discussão do artigo acadêmico: "An exploratory study on assessing the energy impact of logging on Android applications" Empirical Software Engineering June 2018, Volume 23, Issue 3, pp 1422–1456

**Comment by leopoldomt** [comment]
@DouglasSL @JonatasDeOliveira @mcnl @vbsilva @orlandoaceto
Pessoal, lembrem de escolher um dos temas aqui

**Comment by DouglasSL** [comment]
@DouglasSL e @JonatasDeOliveira:  4.Apresentação e discussão do artigo acadêmico: "ServDroid: detecting service usage inefficiencies in Android applications" (ESEC/FSE 2019). DOI: https://doi.org/10.1145/3338906.3338950

**Comment by mcnl** [comment]
@mcnl e @vbsilva: Apresentação e discussão do artigo acadêmico: "Catalog of Energy Patterns for Mobile Applications" accepted at Empirical Software Engineering
