### ISSUE TITLE
Discussão - Testes

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#38]
Por favor, escolham um dos temas disponíveis abaixo:

1. Apresentação e demonstração dos frameworks Espresso e UI Automator, comparando similaridades e diferenças (https://developer.android.com/training/testing)
2. Apresentação e demonstração do framework Appium - http://appium.io
3. Apresentação e demonstração do framework Robotium - https://github.com/RobotiumTech/robotium
4. ~Apresentação e discussão do artigo acadêmico: "How do Developers Test Android Applications?" (ICSME 2017). https://ieeexplore.ieee.org/document/7102609~
5. ~Apresentação e discussão do artigo acadêmico: "To the attention of mobile software developers: guess what, test your app!" Empirical Software Engineering August 2019, Volume 24, Issue 4, pp 2438–2468. https://doi.org/10.1007/s10664-019-09701-0~
6. ~CI mobile, motivações, desafios e soluções~

@ramonsaboya @jfmrm @tancredosouza @dordiogo @arma29 @rafaelmotaalves @heitorado

**Comment by iuribtt** [comment]
Apresentação e discussão do artigo acadêmico: "How do Developers Test Android Applications?" (ICSME 2017). https://ieeexplore.ieee.org/document/7102609

**Comment by iuribtt** [comment]
4. Apresentação e discussão do artigo acadêmico: "How do Developers Test Android Applications?" (ICSME 2017). https://ieeexplore.ieee.org/document/7102609

**Comment by heitorado** [comment]
5. Apresentação e discussão do artigo acadêmico: "To the attention of mobile software developers: guess what, test your app!" Empirical Software Engineering August 2019, Volume 24, Issue 4, pp 2438–2468. https://doi.org/10.1007/s10664-019-09701-0

**Comment by dorDiogo** [comment]
Pelo que vi, iuribtt não está para apresentar nesse tema. Se for isso mesmo, minha dupla quer ficar com o 4.

**Comment by leopoldomt** [comment]
Isso, @dorDiogo - tema 4 está com vocês

**Comment by jfmrm** [comment]
@leopoldomt, o que acha de esplanar o tema de ferramenta de CI + desafios de fazer testes instrumentados pra mobile. Tivemos uma solucão bacana na Inloco há pouco tempo, e assisti também uma palestra de como o pessoal do NuBank resolveu esse problema lá.

**Comment by leopoldomt** [comment]
Oi @jfmrm - vocês podem pegar este tema, sem problemas. Só detalhar um título e preparar o material. ;)

**Comment by jfmrm** [comment]
o título pode ser: "CI mobile, motivações, desafios e soluções"

**Comment by leopoldomt** [comment]
Beleza, @jfmrm - fechado!

**Comment by leopoldomt** [comment]
@arma29 Por favor, escolha o tema de sua preferência para apresentação e discussão em sala.
