### ISSUE TITLE
Discussão - Consumo de Rede

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#39]
Por favor, escolham um dos temas disponíveis abaixo:

1. ~Criação e apresentação de um aplicativo ilustrando anti-patterns relacionados a consumo de rede, ilustrados por meio do Network Profiler do Android Studio (https://developer.android.com/studio/profile/network-profiler)~
2. ~Apresentação e demonstração das bibliotecas OkHttp (https://square.github.io/okhttp/) e Retrofit (https://square.github.io/retrofit/), comparando similaridades e diferenças~
3. ~Apresentação e demonstração da biblioteca Fast Android Networking (https://amitshekhar.me/Fast-Android-Networking/)~
4. Apresentação e discussão do artigo acadêmico: "Navigation-aware and personalized prefetching of network requests in Android apps" (ICSE-NIER '19). DOI: https://doi.org/10.1109/ICSE-NIER.2019.00013
5. ~Apresentação e discussão do artigo acadêmico: "Automated energy optimization of HTTP requests for mobile applications" (ICSE '16). https://doi.org/10.1145/2884781.2884867~

@jailjr @joaoaab @vdcn1 @LucasCCabral @luucasv @AdilsonAngelo @livisghton @akai16

**Comment by luucasv** [comment]
Vamos ficar com o 2.

**Comment by vdcn1** [comment]
@LucasCCabral e eu ficaremos com o 3.

**Comment by akai16** [comment]
Eu e @livisghton vamos ficar com o 1

**Comment by leopoldomt** [comment]
@luucasv @AdilsonAngelo, por favor escolham um tema de sua preferência para apresentar e discutir em sala.

**Comment by leopoldomt** [comment]
@jailjr @joaoaab por favor escolham um tema de sua preferência para apresentar e discutir em sala.

**Comment by jailjr** [comment]
Vamos ficar com o 5.

**Comment by leopoldomt** [comment]
Preenchemos todos os espaços disponíveis para esta aula, portanto, issue fechada.
