### ISSUE TITLE
Discussão - Privacidade & Segurança

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#40]
Por favor, escolham um dos temas disponíveis abaixo:

1. ~Criação e apresentação de aplicativo ilustrando boas práticas relacionadas a privacidade e segurança (https://developer.android.com/topic/security/best-practices | https://source.android.com/security/best-practices)~
2. ~Apresentação e discussão do artigo acadêmico: "The Android Platform Security Model" - https://arxiv.org/abs/1904.05572~
3. ~Apresentação e discussão do artigo acadêmico: "Do Android Taint Analysis Tools Keep their Promises?" (ESEC/FSE ’18). https://www.bodden.de/pubs/pbw18do.pdf~
4. Apresentação e discussão do artigo acadêmico: "On Demystifying the Android Application Framework: Re-Visiting Android Permission Specification Analysis"   - USENIX Security Symposium 2016 https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/backes_android
5. ~Apresentação e discussão do artigo acadêmico: "SoK: Lessons Learned From Android Security Research For Appified Software Platforms" IEEE Symposium on Security and Privacy 2016 - https://oaklandsok.github.io/papers/acar2016.pdf~

@cubsphere @riqgod @vrvs @rllima @lams3 @adecarli @mbs8 @leandroESS

**Comment by mbs8** [comment]
Professor, eu e @leandroESS vamos querer a primeira atividade:

1. Criação e apresentação de aplicativo ilustrando boas práticas relacionadas a privacidade e segurança

**Comment by riqmariz** [comment]
Professor, eu e @cubsphere vamos querer o segundo tema:
2. Apresentação e discussão do artigo acadêmico: "The Android Platform Security Model"

**Comment by leopoldomt** [comment]
@vrvs @rllima @lams3 @adecarli, por favor escolham um tema para discutir e apresentar na aula.

**Comment by adecarli** [comment]
Professor, eu e @lams3 vamos querer o terceiro tema:
3. Apresentação e discussão do artigo acadêmico: "Do Android Taint Analysis Tools Keep their Promises?"

**Comment by leopoldomt** [comment]
@vrvs @rllima por favor indiquem a sua preferência para esta aula.

**Comment by vrvs** [comment]
Professor, eu e @rllima vamos querer o último artigo:
5. Apresentação e discussão do artigo acadêmico: "SoK: Lessons Learned From Android Security Research For Appified Software Platforms" IEEE Symposium on Security and Privacy 2016 - https://oaklandsok.github.io/papers/acar2016.pdf

**Comment by leopoldomt** [comment]
Combinado, @vrvs e @rllima.
