### ISSUE TITLE
Discussão - Acessibilidade

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#41]
Por favor, escolham um dos temas disponíveis abaixo:

1. ~Criação e apresentação de um aplicativo ilustrando boas práticas relacionadas a acessibilidade (https://developer.android.com/guide/topics/ui/accessibility)~
2. ~Apresentação e demonstração das bibliotecas accessibilitools (https://github.com/novoda/accessibilitools) e Axe Android (https://github.com/dequelabs/axe-android)~
3. ~Apresentação e discussão do artigo acadêmico: "AccessiLeaks: Investigating Privacy Leaks Exposed by the Android Accessibility Service" (Privacy Enhancing Technologies Symposium 2019). https://hal.inria.fr/hal-01929049~
4. ~Apresentação e discussão do artigo acadêmico: "Automated Accessibility Testing of Mobile Apps" (ICST 2018). https://ieeexplore.ieee.org/document/8367041~

@michaelbarney @Gui-Lima @marina-barros @jmsmf @tbbruno @lfp2

**Comment by MichaelBarney** [comment]
Desejo ficar com o primeiro: Criação e apresentação de um aplicativo ilustrando boas práticas relacionadas a acessibilidade

**Comment by ZezePSMota** [comment]
Eu e @tbbruno ficaremos com o número 3 (AccessiLeaks)

**Comment by marina-barros** [comment]
Eu e @Gui-Lima desejamos ficar com o número 4: Apresentação e discussão do artigo acadêmico: "Automated Accessibility Testing of Mobile Apps" (ICST 2018)

**Comment by wba25** [comment]
Gostaria de ficar com o número 2: Apresentação e demonstração das bibliotecas accessibilitools (https://github.com/novoda/accessibilitools) e Axe Android (https://github.com/dequelabs/axe-android)

**Comment by lfp2** [comment]
Eu desejo ficar com a apresentação número 2: Apresentação e demonstração das bibliotecas accessibilitools (https://github.com/novoda/accessibilitools) e Axe Android (https://github.com/dequelabs/axe-android)

**Comment by leopoldomt** [comment]
Preenchemos todos os espaços disponíveis para esta aula, portanto, issue fechada.
