### ISSUE TITLE
Discussão - Cross-platform development

### ISSUE THREAD

**Issue by leopoldomt** [if710/if710.github.io#42]
Por favor, escolham um dos temas disponíveis abaixo:

1. ~Apresentação da biblioteca Flutter (https://flutter.dev) por meio da criação de um aplicativo~
2. ~Apresentação da biblioteca React Native (https://facebook.github.io/react-native/) por meio da criação de um aplicativo~
3. ~Apresentação e discussão do artigo acadêmico: "An Empirical Study of Cross-Platform Mobile Development in Industry" - Wireless Communications and Mobile Computing Volume 2019, Article ID 5743892, https://doi.org/10.1155/2019/5743892~
4. ~Apresentação e discussão do artigo acadêmico: "A tale of two fashions: An empirical study on the performance of native apps and web apps on Android." IEEE Transactions on Mobile Computing, 17(5):990--1003, 2018. https://ieeexplore.ieee.org/document/8051099~

@iuribtt @claudiocarvalhoo @hcaula @wba25

**Comment by iuribtt** [comment]
2. Apresentação da biblioteca React Native (https://facebook.github.io/react-native/) por meio da criação de um aplicativo

**Comment by iuribtt** [comment]
4. Apresentação e discussão do artigo acadêmico: "A tale of two fashions: An empirical study on the performance of native apps and web apps on Android." IEEE Transactions on Mobile Computing, 17(5):990--1003, 2018. https://ieeexplore.ieee.org/document/8051099

**Comment by ClaudioCarvalhoo** [comment]
2. Apresentação da biblioteca React Native (https://facebook.github.io/react-native/) por meio da criação de um aplicativo

**Comment by leopoldomt** [comment]
@wba25 por favor escolha um tema para apresentar e discutir em sala.

**Comment by wba25** [comment]
Escolho o número 3: Apresentação e discussão do artigo acadêmico: "An Empirical Study of Cross-Platform Mobile Development in Industry" - Wireless Communications and Mobile Computing Volume 2019, Article ID 5743892, https://doi.org/10.1155/2019/5743892

**Comment by mirianes** [comment]
1. Apresentação da biblioteca Flutter (https://flutter.dev) por meio da criação de um aplicativo
